package View;

import Controller.dataBase;
import Controller.dbBeaches;
import java.util.ArrayList;
import javax.swing.JLabel;

public class menuBeaches extends javax.swing.JFrame {

    public static ArrayList<dbBeaches> beaches = new ArrayList<>();
    
    /**
     * Creates new form MenuBeaches
     */
    public menuBeaches() {
        // Inicializa a lista de praias
        dataBase.Beaches();
        beaches = dataBase.beaches;
        
        initComponents();
        loading();
    }
    
    public void loading() {
        if (!beaches.isEmpty()) {
            namebeache1_txt.setText(beaches.get(0).getName());
            contaminantesbeache1_txt.setText(beaches.get(0).getContaminants());
            phbeache1_txt.setText(String.valueOf(beaches.get(0).pH));
            
            namebeache2_txt.setText(beaches.get(1).getName());
            contaminantesbeache2_txt.setText(beaches.get(1).getContaminants());
            phbeache2_txt.setText(String.valueOf(beaches.get(1).pH));
            
            namebeache3_txt.setText(beaches.get(2).getName());
            contaminantesbeache3_txt.setText(beaches.get(2).getContaminants());
            phbeache3_txt.setText(String.valueOf(beaches.get(2).pH));
        } else {
            namebeache1_txt.setText("No data available");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        contaminantesbeache1_txt = new javax.swing.JLabel();
        phbeache1_txt = new javax.swing.JLabel();
        namebeache1_txt = new javax.swing.JLabel();
        phbeache2_txt = new javax.swing.JLabel();
        contaminantesbeache2_txt = new javax.swing.JLabel();
        namebeache2_txt = new javax.swing.JLabel();
        namebeache3_txt = new javax.swing.JLabel();
        contaminantesbeache3_txt = new javax.swing.JLabel();
        phbeache3_txt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PH");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 20, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 40, 10));

        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 40, 10));

        jLabel4.setText("Presença de contaminantes");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, 20));

        contaminantesbeache1_txt.setText("null");
        getContentPane().add(contaminantesbeache1_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 190, 70));

        phbeache1_txt.setText("null");
        getContentPane().add(phbeache1_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 50, 60));

        namebeache1_txt.setText("null");
        getContentPane().add(namebeache1_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 44, 100, 60));

        phbeache2_txt.setText("null");
        getContentPane().add(phbeache2_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 50, 60));

        contaminantesbeache2_txt.setText("null");
        getContentPane().add(contaminantesbeache2_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 130, 80));

        namebeache2_txt.setText("null");
        getContentPane().add(namebeache2_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 60));

        namebeache3_txt.setText("null");
        getContentPane().add(namebeache3_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, 60));

        contaminantesbeache3_txt.setText("null");
        getContentPane().add(contaminantesbeache3_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 130, 80));

        phbeache3_txt.setText("null");
        getContentPane().add(phbeache3_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 50, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bar.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuBeaches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuBeaches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuBeaches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuBeaches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuBeaches().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contaminantesbeache1_txt;
    private javax.swing.JLabel contaminantesbeache2_txt;
    private javax.swing.JLabel contaminantesbeache3_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JLabel namebeache1_txt;
    private javax.swing.JLabel namebeache2_txt;
    private javax.swing.JLabel namebeache3_txt;
    private javax.swing.JLabel phbeache1_txt;
    private javax.swing.JLabel phbeache2_txt;
    private javax.swing.JLabel phbeache3_txt;
    // End of variables declaration//GEN-END:variables
}
