/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author netoh
 */
public class menuDonate_GUI extends javax.swing.JFrame {

    /**
     * Creates new form menuDonate_GUI
     */
    public menuDonate_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 94, 149));
        jButton1.setText("Clique aqui para doar");
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 220, 40));

        jButton2.setText("Back to menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/donate.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        jButton1.setBackground(new java.awt.Color(143,206,0));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String escolha = JOptionPane.showInputDialog(null, "Digite 1 para praias:\nDigite 2 para rios");
        
        int escolhaInt = Integer.parseInt(escolha);
        String destino = "";

        if (escolhaInt == 1) {
            String opcaoPraia = JOptionPane.showInputDialog(null, "Digite 1 para Peruibe:\nDigite 2 para Copacabana:\nDigite 3 para Jericoacoara :");
            switch (opcaoPraia) {
                case "1":
                    destino = "Peruibe";
                    break;
                case "2":
                    destino = "Copacabana";
                    break;
                case "3":
                    destino = "Jericoacoara";
                    break;
                default:
                    destino = "Opção inválida";
                    break;
            }
        } else if (escolhaInt == 2) {
            String opcaoRio = JOptionPane.showInputDialog(null, "Digite 1 para Tietê:\nDigite 2 para Macaé:\nDigite 3 para Pinheiros :");
            switch (opcaoRio) {
                case "1":
                    destino = "Tietê";
                    break;
                case "2":
                    destino = "Macaé";
                    break;
                case "3":
                    destino = "Pinheiros";
                    break;
                default:
                    destino = "Opção inválida";
                    break;
            }
        } else {
            System.out.println("Escolha inválida.");
            JOptionPane.showMessageDialog(null, "Escolha inválida.");
            return;
        }
    
        String valor = JOptionPane.showInputDialog(null, "Digite o valor:");
        String opcaoPagamento = JOptionPane.showInputDialog(null, "Forma de pagamento:\nDigite 1 para Cartão\nDigite 2 para Pix\nDigite 3 para Boleto");
        
        String formaPagamento = "";
        switch (opcaoPagamento) {
            case "1":
                formaPagamento = "Cartão";
                break;
            case "2":
                formaPagamento = "Pix";
                break;
            case "3":
                formaPagamento = "Boleto";
                break;
            default:
                formaPagamento = "Opção inválida";
                break;
        }
        
        JOptionPane.showMessageDialog(null, "Doação feita com sucesso!, muito obrigado por ajudar nosso planeta.\nDestino: " + destino + "\nForma de Pagamento: " + formaPagamento + "\nValor: R$ " + valor);

       
         dispose(); 

        new menuSelection_GUI().setVisible(true);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new menuSelection_GUI().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuDonate_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuDonate_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuDonate_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuDonate_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuDonate_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
